### ISSUE TITLE
React wrapper for Lit

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/ui#13]
https://custom-elements-everywhere.com/

**Is your feature request related to a problem? Please describe.**

- React does not have complete support for Custom Elements in v18.
- Support will improve. React @experimental version has full support.
- HOT tools may be using an older version anyway & take time to upgrade.

**Describe the solution you'd like**

- We need a wrapper for components to work well in older versions of React <18.
- More info here: https://lit.dev/docs/frameworks/react/

**Additional context**

- Every other framework has full support for Custom Elements (React is lagging behind), so this isn't an issue elsewhere.

**Comment by emi420** [comment]
There's a working version for React in the [feature/react](https://github.com/hotosm/ui/tree/feature/react) branch, but is not at 100% yet.

I tried using lit's createComponent and it works in the Storybook, but not when importing the package from another app.

For the Storybook, there's a new configuration in .storybook-react that displays only the React component. For running it:

**Comment by spwoodcock** [comment]
Nice, that's a great start!

So with this approach we can share the cva styling between Lit components and React components. 

But am I right in saying that the component logic would have to be developed twice? E.g. the click handler.

**Comment by emi420** [comment]
Yes, we can share styling. Click handlers are not necessary for web components but yes for React, so we have to add them. Some other logic could be also shared.
