### ISSUE TITLE
Logo component

### ISSUE THREAD

**Issue by emi420** [hotosm/ui#45]
This component is needed for the Header component

![image](https://github.com/user-attachments/assets/a3eae78a-9f88-4ef1-a15b-bf11412ccfc8)

**Comment by spwoodcock** [comment]
Seems to me this is quite specific to a header, so do we need it as a separate component?

https://github.com/hotosm/ui/blob/12ad2b020ee95e68556f2437141c748ceb7968f9/components/header/header.ts#L41-L45

**Comment by emi420** [comment]
The HOT Logo could be used anywhere, I think is ok to have it as a separated component
