### ISSUE TITLE
Storybook for React

### ISSUE THREAD

**Issue by emi420** [hotosm/ui#54]
While developing components, is not possible to live test them in a React environment.

**Comment by spwoodcock** [comment]
Would this mean another storybook config to maintain? I'm not sure we necessarily need this. 

There are some React examples for React 18 and 19 showing working components. I don't think the web components will work much differently framework to teamwork

**Comment by emi420** [comment]
We need a way to test things while doing development, I can also put the code for this in different repository.

**Comment by emi420** [comment]
The examples are not working good, and important things are missing there, we should remove that directory until we have all things working in a stable way.

**Comment by spwoodcock** [comment]
But we have a storybook already that works fine, no? 😅

**Comment by emi420** [comment]
For web components only, but we have to be sure that things work fine in the different contexts that we want to use the library. I think that having a storybook for both will really help during development.
